#!/usr/bin/env bash

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/project/scripts/.functions.sh"
cd $APP_HOME

PROJECTS=$(dotnet sln list | grep 'csproj$')

for PROJ in $PROJECTS; do
    PROJ=$(dirname "$PROJ")
    cd $PROJ
    rm -fR bin/
    rm -fR obj/
    cd $APP_HOME
done
