#!/usr/bin/env bash

# quiet|minimal|normal|detailed|diagnostic
VERBOSITY=$1
# Debug|Release
CONFIGURATION=Release

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
cd $APP_HOME

if [[ -z "$VERBOSITY" ]]; then VERBOSITY="normal"; fi

cd WebService
dotnet restore
dotnet publish --output bin/docker --configuration $CONFIGURATION --verbosity $VERBOSITY

cd bin/docker
docker build --tag "azureiotpcs/microservice-template-dotnet-ws:1.0-SNAPSHOT" --squash --compress --label "Tags=azure,iot,pcs,.NET" .
