#!/usr/bin/env bash

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
cd $APP_HOME

cd WebService
echo "Starting web service at: http://localhost:5000/api/values"
dotnet run
