language: csharp
mono: none
dotnet: 2.1
os: linux
sudo: false
dist: trusty
addons:
  apt:
    sources:
    packages:
install:
script:
  - dotnet restore
  - dotnet build -c Debug
  - dotnet build -c Release
