language: csharp
mono: none
dotnet: 2.2
os: linux
sudo: false
dist: bionic
osx_image: xcode9.1
addons:
  apt:
    sources:
    packages:
install:
script:
  - dotnet restore "azure-iiot-opc-vault-service.sln"
  - dotnet build -c Debug "azure-iiot-opc-vault-service.sln"
  - dotnet build -c Release "azure-iiot-opc-vault-service.sln"
  - dotnet test -c Release "azure-iiot-opc-vault-service.sln"

