language: csharp
solution: azure-iiot-opc-vault.sln
mono: none
dotnet: 2.2
os:
  - linux
  - osx
sudo: false
dist: bionic
osx_image: xcode9.1
addons:
  apt:
    sources:
    packages:
install:
script: 
  - dotnet restore 
  - dotnet build -c Debug "azure-iiot-opc-vault.sln"
  - dotnet build -c Release "azure-iiot-opc-vault.sln"
  - dotnet test -c Release "azure-iiot-opc-vault.sln"
