language: csharp
mono: none
dotnet: 2.1
os:
  - linux
  - osx
sudo: false
dist: trusty
osx_image: xcode9.1

addons:
  apt:
    sources:
    packages:
script: 
  - echo "========== restore all .Net Core samples ============"
  - dotnet restore "azure-iiot-opc-vault-service.sln"
  - echo "========== build all .Net Core samples ============"
  - dotnet build -c Debug src/Microsoft.Azure.IIot.OpcUa.Services.Vault.csproj
  - dotnet build -c Release src/Microsoft.Azure.IIot.OpcUa.Services.Vault.csproj
  - dotnet test -c Debug --filter TestCategory!="GDSPush" tests
  - dotnet test -c Release --filter TestCategory!="GDSPush" tests

after_script:
  - echo "========== build done ============"


