// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Services.Gds.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ApplicationRecordApiModel
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationRecordApiModel class.
        /// </summary>
        public ApplicationRecordApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationRecordApiModel class.
        /// </summary>
        public ApplicationRecordApiModel(string applicationId = default(string), string applicationUri = default(string), string applicationName = default(string), int? applicationType = default(int?), IList<ApplicationNameApiModel> applicationNames = default(IList<ApplicationNameApiModel>), string productUri = default(string), IList<string> discoveryUrls = default(IList<string>), string serverCapabilities = default(string))
        {
            ApplicationId = applicationId;
            ApplicationUri = applicationUri;
            ApplicationName = applicationName;
            ApplicationType = applicationType;
            ApplicationNames = applicationNames;
            ProductUri = productUri;
            DiscoveryUrls = discoveryUrls;
            ServerCapabilities = serverCapabilities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationId")]
        public string ApplicationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationUri")]
        public string ApplicationUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationName")]
        public string ApplicationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationType")]
        public int? ApplicationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationNames")]
        public IList<ApplicationNameApiModel> ApplicationNames { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductUri")]
        public string ProductUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DiscoveryUrls")]
        public IList<string> DiscoveryUrls { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServerCapabilities")]
        public string ServerCapabilities { get; set; }

    }
}
