// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Services.Gds.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class X509CrlCollectionApiModel
    {
        /// <summary>
        /// Initializes a new instance of the X509CrlCollectionApiModel class.
        /// </summary>
        public X509CrlCollectionApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the X509CrlCollectionApiModel class.
        /// </summary>
        public X509CrlCollectionApiModel(IList<X509CrlApiModel> chain = default(IList<X509CrlApiModel>))
        {
            Chain = chain;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Chain")]
        public IList<X509CrlApiModel> Chain { get; set; }

    }
}
