#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/project-name-here-dotnet:0.1-SNAPSHOT"

# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

compile() {
    check_dependency_dotnet

    cd $APP_HOME
    dotnet restore
    dotnet build --configuration $CONFIGURATION
}

build_docker_image() {
    check_dependency_docker

    cd $APP_HOME

    rm -fR out/docker
    rm -fR WebService/bin/Docker

    mkdir -p out/docker/webservice

    dotnet publish WebService --configuration $CONFIGURATION --output bin/Docker

    cp -pR WebService/bin/Docker/*       out/docker/webservice/

    cp scripts/docker/.dockerignore              out/docker/
    cp scripts/docker/Dockerfile                 out/docker/
    cp scripts/docker/content/run.sh             out/docker/

    cd out/docker/
    docker build --tag "$DOCKER_IMAGE" --squash --compress --label "Tags=azure,iot,pcs,.NET" .
}

compile
build_docker_image

set +e
