#!/usr/bin/env bash -e

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/project-name-here-dotnet"

# Debug|Release
CONFIGURATION=Release

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# The version is stored in a file, to avoid hardcoding it in multiple places
APP_VERSION=$(cat "$APP_HOME/version")

# Whether to update the "latest" tag of the Docker image
UPDATE_LATEST="no"

confirm_version() {
    echo "Building version $APP_VERSION"
    read -r -p "Do you want to update the 'latest' version too? [y/N] " response
    if [[ $response =~ ^[Yy] ]]; then
        UPDATE_LATEST="yes"
    fi
}

compile() {
    check_dependency_dotnet

    cd $APP_HOME
    dotnet restore
    dotnet build --configuration $CONFIGURATION
}

build_docker_image() {
    check_dependency_docker

    cd $APP_HOME

    rm -fR out/docker
    rm -fR WebService/bin/Docker

    mkdir -p out/docker/webservice

    dotnet publish WebService --configuration $CONFIGURATION --output bin/Docker

    cp -pR WebService/bin/Docker/*       out/docker/webservice/

    cp scripts/docker/.dockerignore              out/docker/
    cp scripts/docker/Dockerfile                 out/docker/
    cp scripts/docker/content/run.sh             out/docker/

    cd out/docker/

    if [[ $UPDATE_LATEST == "no" ]]; then
        docker build --tag "$DOCKER_IMAGE:$APP_VERSION" --squash --compress --label "Tags=azure,iot,pcs,.NET" .
    else
        docker build --tag "$DOCKER_IMAGE:$APP_VERSION" --tag "$DOCKER_IMAGE:latest" --squash --compress --label "Tags=Azure,IoT,Solutions,.NET" .
    fi

    echo "Run './scripts/docker/publish' to publish the image to the registry"
}

confirm_version
compile
build_docker_image

set +e
