# You can use this file to setup the service locally, and start all the
# containers at once.
#
# Usage:
# - setup all the environment variables referenced below
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  dependencyone:
    image: azureiotpcs/dependencyone:0.x.y
    ports:
      - "9001:9001"
  dependencytwo:
    image: azureiotpcs/dependencytwo:0.x.y
    ports:
      - "9002:9002"
    environment:
      - PCS_IOTHUB_CONNSTRING
  dependencythree:
    image: azureiotpcs/dependencythree:0.x.y
    depends_on:
      - dependencyone
    ports:
      - "9003:9003"
  opcgds:
    image: azureiotpcs/opc-gds-dotnet:0.x.y
    depends_on:
      - dependencyone
      - dependencytwo
      - dependencythree
    ports:
      - "54321:54321"
    environment:
      - PCS_DEPENDENCYONE_WEBSERVICE_URL=http://dependencyone:9001/v1
      - PCS_DEPENDENCYTWO_WEBSERVICE_URL=http://dependencytwo:9002/v1
      - PCS_DEPENDENCYTHREE_WEBSERVICE_URL=http://dependencythree:9003/v1
