// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace GdsVault.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class QueryServersApiModel
    {
        /// <summary>
        /// Initializes a new instance of the QueryServersApiModel class.
        /// </summary>
        public QueryServersApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryServersApiModel class.
        /// </summary>
        public QueryServersApiModel(int? startingRecordId = default(int?), int? maxRecordsToReturn = default(int?), string applicationName = default(string), string applicationUri = default(string), string productUri = default(string), IList<string> serverCapabilities = default(IList<string>))
        {
            StartingRecordId = startingRecordId;
            MaxRecordsToReturn = maxRecordsToReturn;
            ApplicationName = applicationName;
            ApplicationUri = applicationUri;
            ProductUri = productUri;
            ServerCapabilities = serverCapabilities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartingRecordId")]
        public int? StartingRecordId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxRecordsToReturn")]
        public int? MaxRecordsToReturn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationName")]
        public string ApplicationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationUri")]
        public string ApplicationUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductUri")]
        public string ProductUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServerCapabilities")]
        public IList<string> ServerCapabilities { get; set; }

    }
}
