// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 2.4.43.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Services.GdsVault.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class QueryServersResponseApiModel
    {
        /// <summary>
        /// Initializes a new instance of the QueryServersResponseApiModel
        /// class.
        /// </summary>
        public QueryServersResponseApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryServersResponseApiModel
        /// class.
        /// </summary>
        public QueryServersResponseApiModel(IList<ServerOnNetworkApiModel> servers = default(IList<ServerOnNetworkApiModel>), System.DateTime? lastCounterResetTime = default(System.DateTime?))
        {
            Servers = servers;
            LastCounterResetTime = lastCounterResetTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Servers")]
        public IList<ServerOnNetworkApiModel> Servers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastCounterResetTime")]
        public System.DateTime? LastCounterResetTime { get; set; }

    }
}
