#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

if [[ ${#APP_HOME} -lt 20 ]]; then
    error "Unable to detect current folder. Aborting."
    exit 1
fi

reset_cache() {
    cd $APP_HOME

    rm -fR .cache

    mkdir -p .cache/sandbox/.config
    echo "*" > .cache/sandbox/.config/.gitignore
    echo "!.gitignore" >> .cache/sandbox/.config/.gitignore

    mkdir -p .cache/sandbox/.dotnet
    echo "*" > .cache/sandbox/.dotnet/.gitignore
    echo "!.gitignore" >> .cache/sandbox/.dotnet/.gitignore

    mkdir -p .cache/sandbox/.nuget
    echo "*" > .cache/sandbox/.nuget/.gitignore
    echo "!.gitignore" >> .cache/sandbox/.nuget/.gitignore
}

cleanup_tmp_files() {
    check_dependency_dotnet

    cd $APP_HOME
    header "Removing temporary folders and files..."

    rm -fR packages

    PROJECTS=$(dotnet sln list | grep 'csproj$')
    for PROJ in $PROJECTS; do
        PROJ=$(dirname "$PROJ")
        cd $PROJ
        rm -fR bin/
        rm -fR obj/
        cd $APP_HOME
    done

    echo "Done"
}

cleanup_tmp_files
reset_cache

set +e
