#!/usr/bin/env bash

EXT_PORT=8080

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

setup_cache() {
    cd $APP_HOME
    mkdir -p .cache/sandbox/.config
    mkdir -p .cache/sandbox/.dotnet
    mkdir -p .cache/sandbox/.nuget
}

run_in_sandbox() {
    check_dependency_docker

    docker run -it \
        -p $EXT_PORT:8080 \
        -e "PCS_IOTHUB_CONN_STRING=$PCS_IOTHUB_CONN_STRING" \
        -v $APP_HOME/.cache/sandbox/.config:/root/.config \
        -v $APP_HOME/.cache/sandbox/.dotnet:/root/.dotnet \
        -v $APP_HOME/.cache/sandbox/.nuget:/root/.nuget \
        -v $APP_HOME:/opt/code \
        azureiotpcs/code-builder-dotnet:1.0 /opt/scripts/run
}

setup_cache
run_in_sandbox

set +e
