// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Api.Vault.v1.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ApplicationType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ApplicationType
    {
        /// <summary></summary>
        [EnumMember(Value = "server")]
        Server,
        /// <summary></summary>
        [EnumMember(Value = "client")]
        Client,
        /// <summary></summary>
        [EnumMember(Value = "clientAndServer")]
        ClientAndServer,
        /// <summary></summary>
        [EnumMember(Value = "discoveryServer")]
        DiscoveryServer
    }
    internal static class ApplicationTypeEnumExtension
    {
        internal static string ToSerializedValue(this ApplicationType? value)
        {
            return value == null ? null : ((ApplicationType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ApplicationType value)
        {
            switch( value )
            {
                case ApplicationType.Server:
                    return "server";
                case ApplicationType.Client:
                    return "client";
                case ApplicationType.ClientAndServer:
                    return "clientAndServer";
                case ApplicationType.DiscoveryServer:
                    return "discoveryServer";
            }
            return null;
        }

        internal static ApplicationType? ParseApplicationType(this string value)
        {
            switch( value )
            {
                case "server":
                    return ApplicationType.Server;
                case "client":
                    return ApplicationType.Client;
                case "clientAndServer":
                    return ApplicationType.ClientAndServer;
                case "discoveryServer":
                    return ApplicationType.DiscoveryServer;
            }
            return null;
        }
    }
}
