// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Api.Vault.v1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary></summary>
    public partial class CertificateRequestRecordApiModel
    {
        /// <summary>
        /// Initializes a new instance of the CertificateRequestRecordApiModel
        /// class.
        /// </summary>
        public CertificateRequestRecordApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CertificateRequestRecordApiModel
        /// class.
        /// </summary>
        /// <param name="state">Possible values include: 'new', 'approved',
        /// 'rejected', 'accepted', 'deleted', 'revoked', 'removed'</param>
        /// <param name="signingRequest"></param>
        /// <param name="requestId"></param>
        /// <param name="applicationId"></param>
        /// <param name="groupId"></param>
        /// <param name="certificateType"></param>
        /// <param name="subjectName"></param>
        /// <param name="domainNames"></param>
        /// <param name="privateKeyFormat"></param>
        public CertificateRequestRecordApiModel(CertificateRequestState state, bool signingRequest, string requestId = default(string), string applicationId = default(string), string groupId = default(string), string certificateType = default(string), string subjectName = default(string), IList<string> domainNames = default(IList<string>), string privateKeyFormat = default(string))
        {
            RequestId = requestId;
            ApplicationId = applicationId;
            State = state;
            GroupId = groupId;
            CertificateType = certificateType;
            SigningRequest = signingRequest;
            SubjectName = subjectName;
            DomainNames = domainNames;
            PrivateKeyFormat = privateKeyFormat;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public string ApplicationId { get; set; }

        /// <summary>
        /// Gets possible values include: 'new', 'approved', 'rejected',
        /// 'accepted', 'deleted', 'revoked', 'removed'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public CertificateRequestState State { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupId")]
        public string GroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certificateType")]
        public string CertificateType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "signingRequest")]
        public bool SigningRequest { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subjectName")]
        public string SubjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "domainNames")]
        public IList<string> DomainNames { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "privateKeyFormat")]
        public string PrivateKeyFormat { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
