// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Api.Vault.v1.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CertificateRequestState.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CertificateRequestState
    {
        /// <summary></summary>
        [EnumMember(Value = "new")]
        New,
        /// <summary></summary>
        [EnumMember(Value = "approved")]
        Approved,
        /// <summary></summary>
        [EnumMember(Value = "rejected")]
        Rejected,
        /// <summary></summary>
        [EnumMember(Value = "accepted")]
        Accepted,
        /// <summary></summary>
        [EnumMember(Value = "deleted")]
        Deleted,
        /// <summary></summary>
        [EnumMember(Value = "revoked")]
        Revoked,
        /// <summary></summary>
        [EnumMember(Value = "removed")]
        Removed
    }
    internal static class CertificateRequestStateEnumExtension
    {
        internal static string ToSerializedValue(this CertificateRequestState? value)
        {
            return value == null ? null : ((CertificateRequestState)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CertificateRequestState value)
        {
            switch( value )
            {
                case CertificateRequestState.New:
                    return "new";
                case CertificateRequestState.Approved:
                    return "approved";
                case CertificateRequestState.Rejected:
                    return "rejected";
                case CertificateRequestState.Accepted:
                    return "accepted";
                case CertificateRequestState.Deleted:
                    return "deleted";
                case CertificateRequestState.Revoked:
                    return "revoked";
                case CertificateRequestState.Removed:
                    return "removed";
            }
            return null;
        }

        internal static CertificateRequestState? ParseCertificateRequestState(this string value)
        {
            switch( value )
            {
                case "new":
                    return CertificateRequestState.New;
                case "approved":
                    return CertificateRequestState.Approved;
                case "rejected":
                    return CertificateRequestState.Rejected;
                case "accepted":
                    return CertificateRequestState.Accepted;
                case "deleted":
                    return CertificateRequestState.Deleted;
                case "revoked":
                    return CertificateRequestState.Revoked;
                case "removed":
                    return CertificateRequestState.Removed;
            }
            return null;
        }
    }
}
