// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Api.Vault.v1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary></summary>
    public partial class CreateSigningRequestApiModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateSigningRequestApiModel
        /// class.
        /// </summary>
        public CreateSigningRequestApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateSigningRequestApiModel
        /// class.
        /// </summary>
        public CreateSigningRequestApiModel(string applicationId = default(string), string groupId = default(string), string certificateType = default(string), string certificateRequest = default(string))
        {
            ApplicationId = applicationId;
            GroupId = groupId;
            CertificateType = certificateType;
            CertificateRequest = certificateRequest;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public string ApplicationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupId")]
        public string GroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certificateType")]
        public string CertificateType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certificateRequest")]
        public string CertificateRequest { get; set; }

    }
}
