// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//

namespace Microsoft.Azure.IIoT.OpcUa.Api.Vault.v1 {

    /// <summary></summary>
    public class OpcVaultApiOptions {
        /// <summary></summary>
        public string ResourceId { get; set; }
        /// <summary></summary>
        public string BaseAddress { get; set; }
    }
}
